In [222]:
#1
from sklearn.datasets import load_breast_cancer

my_data = load_breast_cancer()


In [223]:
#2
from sklearn.manifold import TSNE
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [224]:
#3
from sklearn.model_selection import train_test_split
import numpy as np


X = np.random.rand(100, 5)
y = np.random.randint(0, 2, size=100)

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,

    test_size=0.2,
    random_state=42,
    shuffle=True,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)


X_train shape: (80, 5)
X_test shape: (20, 5)
y_train shape: (80,)
y_test shape: (20,)


In [226]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

# טעינת הנתונים
data = load_breast_cancer()
X = data.data
y = data.target

# חלוקת הנתונים
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# יצירת המודל עם הפרמטרים הרצויים
model = DecisionTreeClassifier(
    criterion='entropy',
    splitter='best',
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    min_weight_fraction_leaf=0.0,
    max_features=None,
    random_state=42,
    max_leaf_nodes=15,
    min_impurity_decrease=0.0,
    class_weight={0: 1, 1: 2},
    ccp_alpha=0.01
)

# אימון המודל על נתוני האימון
model.fit(X_train, y_train)

# חיזוי על סט הבדיקה
y_test_pred = model.predict(X_test)

# חישוב מדדים והדפסתם
# 1. Accuracy
accuracy = accuracy_score(y_test, y_test_pred)
print(f"Accuracy: {accuracy:.2f}")

# 2. Precision
precision = precision_score(y_test, y_test_pred, average='binary')
print(f"Precision: {precision:.2f}")

# 3. Recall
recall = recall_score(y_test, y_test_pred, average='binary')
print(f"Recall: {recall:.2f}")

# 4. F1-Score
f1 = f1_score(y_test, y_test_pred, average='binary')
print(f"F1-Score: {f1:.2f}")

# 5. Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_test_pred)
print("\nConfusion Matrix:")
print(conf_matrix)


Accuracy: 0.93
Precision: 0.94
Recall: 0.94
F1-Score: 0.94

Confusion Matrix:
[[38  4]
 [ 4 68]]


In [227]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = RandomForestClassifier(
    n_estimators=300,
    criterion='entropy',
    max_depth=20,
    min_samples_split=4,
    min_samples_leaf=2,
    min_weight_fraction_leaf=0.0,
    max_features='sqrt',
    max_leaf_nodes=None,
    min_impurity_decrease=0.001,
    bootstrap=True,
    oob_score=True,
    n_jobs=-1,
    random_state=42,
    verbose=0,
    warm_start=False,
    class_weight='balanced',
    ccp_alpha=0.0005,
    max_samples=0.95
)

model.fit(X_train, y_train)

y_test_pred = model.predict(X_test)
test_accuracy = accuracy_score(y_test, y_test_pred)

print(f"Test Accuracy: {test_accuracy:.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_test_pred, target_names=data.target_names))


Test Accuracy: 0.96

Classification Report:
              precision    recall  f1-score   support

   malignant       0.95      0.93      0.94        42
      benign       0.96      0.97      0.97        72

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114



In [228]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report

# יצירת נתונים
X, y = make_classification(
    n_samples=1000,
    n_features=20,
    n_informative=15,
    n_redundant=5,
    random_state=42
)

# חלוקת הנתונים
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# מודל בסיסי של DecisionTree
base_estimator = DecisionTreeClassifier(
    max_depth=3,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

# הגדרת AdaBoost
model = AdaBoostClassifier(
    estimator=base_estimator,
    n_estimators=200,
    learning_rate=0.1,
    algorithm='SAMME.R',
    random_state=42
)

# אימון המודל
model.fit(X_train, y_train)

# חיזוי
y_test_pred = model.predict(X_test)

# הערכת המודל
accuracy = accuracy_score(y_test, y_test_pred)
print(f"Test Accuracy: {accuracy:.2f}")
print("\nClassification Report:")
print(classification_report(y_test, y_test_pred))


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


Test Accuracy: 0.90

Classification Report:
              precision    recall  f1-score   support

           0       0.89      0.92      0.91       106
           1       0.91      0.87      0.89        94

    accuracy                           0.90       200
   macro avg       0.90      0.90      0.90       200
weighted avg       0.90      0.90      0.90       200



In [229]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# Generate synthetic dataset
X, y = make_classification(n_samples=1000, n_features=20, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize models
model_decision_tree = DecisionTreeClassifier(max_depth=5, random_state=42)
model_random_forest = RandomForestClassifier(n_estimators=100, max_depth=15, random_state=42)
model_adaboost = AdaBoostClassifier(n_estimators=100, learning_rate=0.5, random_state=42)

# Train models
models = {
    "Decision Tree": model_decision_tree,
    "Random Forest": model_random_forest,
    "AdaBoost": model_adaboost
}

metrics = {}

for name, model in models.items():
    # Train and predict
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')
    confusion = confusion_matrix(y_test, y_pred)

    metrics[name] = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1,
        "Confusion Matrix": confusion
    }

# Print metrics for each model
for name, metric in metrics.items():
    print(f"\n{name}:")
    for key, value in metric.items():
        if key == "Confusion Matrix":
            print(f"  {key}:\n{value}")
        else:
            print(f"  {key}: {value:.2f}")

# Determine the best model based on F1-Score
decisive_metric = "F1-Score"
winner = max(metrics, key=lambda x: metrics[x][decisive_metric])

print(f"\nThe best model is: {winner} with {decisive_metric} = {metrics[winner][decisive_metric]:.2f}")


/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(



Decision Tree:
  Accuracy: 0.88
  Precision: 0.88
  Recall: 0.88
  F1-Score: 0.88
  Confusion Matrix:
[[85  8]
 [17 90]]

Random Forest:
  Accuracy: 0.90
  Precision: 0.90
  Recall: 0.90
  F1-Score: 0.90
  Confusion Matrix:
[[88  5]
 [16 91]]

AdaBoost:
  Accuracy: 0.84
  Precision: 0.84
  Recall: 0.84
  F1-Score: 0.84
  Confusion Matrix:
[[81 12]
 [20 87]]

The best model is: Random Forest with F1-Score = 0.90
